version: '3.8'

services:
  # ==========================================
  # DATABASE: PocketBase
  # ==========================================
  roadtrip-db:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: roadtrip-db
    restart: always
    volumes:
      - ./pb_data:/pb_data
      - ./pb_public:/pb_public
    networks:
      - default
    healthcheck:
      test: [ "CMD", "wget", "--spider", "-q", "http://127.0.0.1:8090/api/health" ]
      interval: 10s
      timeout: 5s
      retries: 3

  # ==========================================
  # FRONTEND: Nuxt 3 App PWA
  # ==========================================
  roadtrip:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: roadtrip
    restart: always
    environment:
      - NODE_ENV=production
      - HOST=0.0.0.0
      # Docker va mapper automatiquement avec ton fichier .env local 🪄
      - NUXT_APP_PIN_CODE=${NUXT_APP_PIN_CODE}
      - NUXT_PUBLIC_POCKETBASE_URL=${NUXT_PUBLIC_POCKETBASE_URL}
      - POCKETBASE_INTERNAL_URL=${POCKETBASE_INTERNAL_URL}
      - NUXT_OPENWEATHER_API_KEY=${NUXT_OPENWEATHER_API_KEY}
    networks:
      - default
    depends_on:
      roadtrip-db:
        condition: service_healthy

networks:
  default:
    external:
      name: proxy_network